feishu:
  # 该区域请于飞书开放平台查询本机器人信息,详见
  # https://open.feishu.cn/document/home/develop-a-bot-in-5-minutes/coding
  APP_ID: cli_a3848cf069b9900e
  APP_SECRET: ygBBDJB2NqGFPVG5Vi9nlhlgggekhqNf
  VERIFICATION_TOKEN: ''
  ENCRYPT_KEY: ''
  LARK_HOST: "https://open.feishu.cn"

server:
  # 端口，请根据实际情况为准
  PORT: 3000
